# Generated by Django 4.1.1 on 2022-09-09 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Leads', '0004_alter_userlead_agent_lead'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlead',
            name='profile_lead',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Leads.userprofile'),
            preserve_default=False,
        ),
    ]
