# Generated by Django 4.1.1 on 2022-09-10 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Leads', '0007_usercategory_userlead_caategory_lead'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercategory',
            name='category_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Leads.userprofile'),
        ),
    ]
