# Generated by Django 4.1.1 on 2022-09-10 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Leads', '0008_usercategory_category_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercategory',
            name='category_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Leads.userprofile'),
        ),
    ]
