# Generated by Django 4.1.1 on 2022-09-10 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Leads', '0009_alter_usercategory_category_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userlead',
            old_name='caategory_lead',
            new_name='category_lead',
        ),
    ]
