# Generated by Django 4.1.1 on 2022-09-10 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Leads', '0010_rename_caategory_lead_userlead_category_lead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlead',
            name='category_lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='UserLead', to='Leads.usercategory'),
        ),
    ]
